---
galaxy_info:
  author: guionardo
  description: Installs Docker CE, Compose v2, Buildx, and adds users to docker group
  license: MIT
  min_ansible_version: '2.14'
  platforms:
    - name: Debian
      versions:
        - trixie
        - bookworm
dependencies: []
